routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/welcome', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'todoController@index');

Route::resource('todo', 'todoController');

Route::post('/todo/change-status/{id}/{status}', 'todoController@changeStatus')->name('todo.changestatus');

app/Todo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Todo extends Model
{
    protected $table = 'todo';

    public function user() {
    	return $this->hasOne('App\User', 'id', 'user_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function todos() {
        return $this->hasMany('App\Todo', 'user_id', 'id');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        // Gaunu prisijungusio zmogaus ID
        $userID = Auth::user()->id;
        $userTasks = user::find($userID)->todos;

        return view('home', ['userTasks' => $userTasks]);
    }
}

app/Http/Controllers/todoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Todo;
use App\User;
use Mail;

class todoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $todoItems = Todo::all();

        $allUsers = User::all();


        return view('todo.index', [
            'todo' => $todoItems,
            'allUsers' => $allUsers,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

     /**
    id - todo list item id
    status - status of item
        -- 0 = undone
        -- 1 = done
        -- 2 = waiting for review 
    */
    public function changeStatus($id, $status) {
        $item = Todo::find($id);

        $item->status = $status;

        $item->save();

        return redirect()->route('todo.index');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $item = new Todo();

        $item->title = $request->title;

        $item->user_id = $request->user_id;

        $item->save();

        // issiusti emaila vartotojui kuriam priskrta uzduotis
        $this->sendEmailNotification($request->user_id, $item->id);

        return redirect()->route('todo.index');
    }

    public function sendEmailNotification($user_id, $todo_id) {
        global $userEmail;
        $userEmail = User::find($user_id)->email;

        $todoItem = Todo::find($todo_id);

        $data = [];

        $data['todo'] = $todoItem;


        Mail::send('mail', $data, function($message) {
            global $userEmail;

         $message->to($userEmail, 'Administratorius')->subject
            ('Priskirta nauja uzduotis');

         $message->from('popiezius@gmail.com','Popiezius');
         $message->replyTo('Invulmode.online@gmail.com', 'Modestas');
      });
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $todo = Todo::find($id);

        $todo->delete();

        return redirect()->route('todo.index');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <h3>Jusu uzduotys</h3>
                    <ul>
                    @foreach($userTasks as $item)
                        <li>{{ $item->title }}</li>
                    @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-126269526-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-126269526-1');
    </script>
    
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/mail.blade.php
<h1>Labas </h1>

Jums priskirta nauja uzduotis: {{ $todo->title }}

<a href="http://projektas.laravel/public/todo">Perziureti</a>

resources/views/todo/createForm.blade.php
<form action="{{ route('todo.store') }}" method="POST">

	{{ csrf_field() }}
	<div class="row">
	<div class="col-md-8">
	<div class="form-group">
		<input type="text" class="form-control" placeholder="Iveskite uzduoties pavadinima" name="title">
	</div>
	<div class="form-group">
		<select name="user_id">
			@foreach($allUsers as $user)
				<option value="{{ $user->id }}">{{ $user->name }}</option>
			@endforeach
		</select>
	</div>
	</div>
	<div class="col-md-4">
		<input type="submit"  value="Ivesti" class="btn btn-info">
	</div>
</div>

</form>

resources/views/todo/index.blade.php
@extends ('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">

	@include('todo.createForm')
	<h1> Visos Užduotys </h1>
	@foreach($todo as $item)
		<div class="todo-item row mt-3 {{ $item->status==1 ? 'done' : '' }}">
			<div class="col-md-3">
				@include('todo.taskbuttons')
			</div>
			<div class="col-md-6 task-">
				{{ $item->title }} 
				<br>
				@if(isset($item->user))
					Priskirta: {{ $item->user->name }}
				@endif
			</div>
			<div class="col-md-3">

				<form action="{{ route('todo.destroy', $item->id) }}" method="POST">
					{{ csrf_field() }}
					{{ method_field('delete')}}
				<input type="submit" value="X" class="btn btn-danger">
				</form>
			</div>
			
		</div>
	@endforeach

</div>
</div>

@endsection

resources/views/todo/taskbuttons.blade.php
@if($item->status == 1)
	<button class="btn info">Uzduotis atlikta</button>
	<form action="{{ route('todo.changestatus', [$item->id, 0])}}" method="POST">
		{{ csrf_field() }}
		<input type="submit" value="Padaryti kaip nebaigta" class="btn btn-success">
	</form>
@else
	<form action="{{ route('todo.changestatus', [$item->id, 1])}}" method="POST">
		{{ csrf_field() }}
		<input type="submit" value="Baigti" class="btn btn-success">
	</form>
@endif